my_string = input("как дела?" )
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string.replace("good" ," "))
print(my_string.replace("very" ," "))
